# Render Deployment Configuration

web:
  - name: footoshop-backend
    env: docker
    buildCommand: ""
    startCommand: "deno run --allow-net --allow-read --allow-write app.ts"
    envVars:
      - key: PORT
        value: 8000
      - key: DENO_DEPLOY
        value: true
    rootDir: backend

static:
  - name: footoshop-frontend  
    rootDir: frontend
    buildCommand: ""
    publishDir: .
